- src/app/layout.tsx
> fix: viewportのwarning対応

- README.md
開発環境構築の方法を記載しました。
https://github.com/exKAZUu-Research/trace-dojo/blob/chore-add-getting-started/README.md
> docs: Add Getting Started

- src/app/(withAuth)/courses/page.tsx
- src/app/auth/[[...path]]/page.tsx
- src/asyncFunctions/cache/actions.ts
- src/components/organisms/Providers.tsx
- src/components/organisms/SignOutMenuItem.tsx
- src/infrastructures/supertokens/frontendConfig.ts
> fix: invalidate cache when sign in/up/out

- src/app/(withAuth)/courses/[courseId]/page.tsx
- src/app/(withAuth)/courses/page.tsx
- src/problems/problemData.ts
> feat: add course, lesson and problem data

- src/app/(withAuth)/courses/page.tsx
https://github.com/orgs/exKAZUu-Research/projects/1/views/1?pane=issue&itemId=49626868
`Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.` の対応
> fix: Course list warning

- src/app/lib/solveProblem.ts
- src/components/organisms/TurtleGraphics.tsx
- src/types.ts
- tests/solveProblem.test.ts
回答の生成を修正し、複数のキャラクターが登場するプログラムに対応しました。
> feat: Support multiple characters in solveProblem

- src/app/lib/Character.ts
- src/app/lib/solveProblem.ts
正誤判定からキャラクターの移動の過程を除外し、併せてCharacterクラスからpathを削除しました。
> fix: Remove path property from Character class

- src/app/(withAuth)/courses/[courseId]/Course.tsx
Close #39
レッスン（第x回）ごとに進捗を表示しました。
> feat: display lesson progress

- src/app/(withAuth)/courses/[courseId]/programs/[programId]/CheckpointProblem.tsx
- src/app/(withAuth)/courses/[courseId]/programs/[programId]/ExecutionResultProblem.tsx
- src/app/(withAuth)/courses/[courseId]/programs/[programId]/StepProblem.tsx
- src/app/(withAuth)/courses/[courseId]/programs/[programId]/page.tsx
- src/problems/problemData.ts
- src/types.ts
Close #13 
いくつか相談したいことがあります。（まだ実装途中です。コードを直した方がいい箇所があったら随時指摘していただきたいです。）
javaを表示するときなど、コードを表示する関数とコードを表示するコンポーネントに渡すコードが異なることがあるので分ける必要があると感じました。
そこで、`generateProgram`関数では以下のようなオブジェクトを返し、`problemProgram`でも以下のようなオブジェクトを保存するのがよいと考えました。
```
{
displayProgram: string,
excuteProgram: string,
}
```
`ExecutionResultProblem`などの各コンポーネントにおいて実行する関数と表示するコンポーネントにそれぞれのコードを渡したいため、`generateProgram`関数では上のオブジェクトを返そうと思っています。
実際にコードを表示してみて採点してみたところ正解の図であるにも関わらず、不正解と言われてしまいました。
原因がわからないので教えていただきたいです。
> feat: The user can view the program that embodies the variable part (e.g. <3-5>) of the problem (program template)

- prisma/migrations/20240304085532_change_finished_at_not_require/migration.sql
- prisma/schema.prisma
- src/app/(withAuth)/courses/[courseId]/programs/[programId]/page.tsx
- src/app/lib/actions.ts
問題開始時に、UserProblemSessionのレコードを作成するようにしました。
問題種別が変更されたとき・チェックポイントやステップが変更されたときにUserProblemSessionのレコードを更新するようにしました。
> feat: Create UserProblemSession Record

- src/app/(withAuth)/courses/[courseId]/Course.tsx
- src/app/(withAuth)/courses/[courseId]/page.tsx
- src/app/(withAuth)/courses/[courseId]/programs/[programId]/CheckpointProblem.tsx
- src/app/(withAuth)/courses/[courseId]/programs/[programId]/ExecutionResultProblem.tsx
- src/app/(withAuth)/courses/[courseId]/programs/[programId]/StepProblem.tsx
- src/app/(withAuth)/courses/[courseId]/programs/[programId]/page.tsx
- src/app/lib/SessionStorage.ts
- src/app/lib/actions.ts
- src/components/molecules/CustomModal.tsx
- src/components/organisms/TurtleGraphics.tsx
- src/problems/problemData.ts
- src/types.ts
- tests/problemData.test.ts
> refactor: make type definitions stricter

- src/tracer/traceProgram.ts
- tests/traceCode.test.ts
> fix: make traceProgram() not stringify turtles

- tests/traceCode.test.ts
> refactor: tests

- src/app/(withAuth)/courses/[courseId]/programs/[programId]/BaseProblem.tsx
アイドル時にボードがリセットされてしまう問題を修正しました。
> fix: Prevent board from resetting in onIdle function

- src/components/molecules/TurtleGraphicsController.tsx
- src/components/organisms/TurtleGraphics.tsx
> feat: 後ろに戻るためのボタンを追加する

- src/components/molecules/TurtleGraphicsController.tsx
- src/components/organisms/TurtleGraphics.tsx
| Current                  | In coming                |
| ------------------------ | ------------------------ |
| ![スクリーンショット 2024-09-10 174536](https://github.com/user-attachments/assets/508d76e5-3ad4-4bc7-b372-62e6cfa078ba) | ![スクリーンショット 2024-09-10 174348](https://github.com/user-attachments/assets/70fa721a-9977-41c8-ab6e-6944dd9ada85) |
> fix: 色の選択機能を削除する

- src/components/organisms/TurtleGraphics.tsx
- src/problems/traceProgram.ts
1. http://localhost:3000/courses/tuBeginner1/java/straight を開きログインする。
2. 左下にカメをセットして問題を解く。
> fix: 亀の初期状態をスライドに合わせる

- src/app/(withAuth)/courses/[courseId]/[languageId]/[programId]/CheckpointProblem.tsx
- src/app/(withAuth)/courses/[courseId]/[languageId]/[programId]/StepProblem.tsx
| Current                  | In coming                |
| ------------------------ | ------------------------ |
| ![スクリーンショット 2024-09-10 174459](https://github.com/user-attachments/assets/45d98641-c7b5-4897-b09f-6632e84bbec7) | ![スクリーンショット 2024-09-10 174258](https://github.com/user-attachments/assets/dda95ef1-1eab-4118-84af-e25f3287b4d9)|
> fix: 一発正解できなかった際に表示される問題の盤面の表示順序を入れ替える

- src/app/(withAuth)/courses/[courseId]/[languageId]/[programId]/CheckpointProblem.tsx
- src/app/(withAuth)/courses/[courseId]/[languageId]/[programId]/StepProblem.tsx
- src/components/organisms/SyntaxHighlighter.tsx
| Current                  | In coming                |
| ------------------------ | ------------------------ |
| ![image](https://github.com/user-attachments/assets/3952e752-bfc3-4d9a-8def-a7ccdfe8b824) | ![スクリーンショット 2024-09-12 200934](https://github.com/user-attachments/assets/4dc10611-d170-408a-ad25-3b90f263b1e7) |
> feat: 前回の実行箇所と現在の実行箇所が被っていることが認識できるようにする

- src/constants.ts
| Current                  | In coming                |
| ------------------------ | ------------------------ |
| ![image](https://github.com/user-attachments/assets/9a55fc7c-7ce9-4d72-802c-78689c7cdfe4) | ![スクリーンショット 2024-09-13 121656](https://github.com/user-attachments/assets/c3d1254d-9f9b-4425-abfe-5a8ad42e1f6e)|
> fix: 盤面のサイズ（マスの数）をスライドに合わせる

- package.json
- src/app/(withAuth)/courses/[courseId]/Course.tsx
- src/app/(withAuth)/courses/[courseId]/[languageId]/[programId]/BaseProblem.tsx
- src/app/(withAuth)/courses/[courseId]/[languageId]/[programId]/page.tsx
- src/app/(withAuth)/courses/[courseId]/page.tsx
- src/app/lib/actions.ts
- src/infrastructures/trpcBackend/client.ts
- src/infrastructures/trpcBackend/routers/index.ts
- src/infrastructures/trpcBackend/trpc.ts
- src/utils/fetch.ts
- src/utils/upsertUserProblemSession.ts
- yarn.lock
> perf: Server Actions を tRPC に移行する

- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/ProblmBody.tsx
- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/SyntaxHighlighter.tsx
> fix: use border instead of highlight for currentFocusLine

- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/BoardEditor.tsx
> feat: 削除ボタンをタートルを削除に変える

- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/BoardEditor.tsx
> feat: ボタン群の下に赤字で「右クリックでマスを白色に戻せます。」を表示する

- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/page.tsx
- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/pageOnClient.tsx
- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/BoardEditor.tsx
- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/ProblmBody.tsx
- src/constants.ts
- src/infrastructures/trpcBackend/routers/index.ts
> feat: 一発解答モードに3回挑戦できるようにする

- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/BoardEditor.tsx
- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/ProblmBody.tsx
- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/Variables.tsx
- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/pageOnClient.tsx
> feat: 変数情報を操作盤面の下に移動する

- src/app/(withAuth)/courses/[courseId]/lectures/[lectureId]/problems/[problemId]/ProblmBody.tsx
> fix: improve UIs for step execution

- src/problems/problemData.ts
> feat: add problems for lecture 4

- src/problems/problemData.ts
- tests/unit/problemData.test.ts
> feat: add problems for lectures 5 and 6

- src/problems/problemData.ts
> feat: Ⅱの第2回のスライドの一部のコードの追加

- src/problems/problemData.ts
> fix: 第1回ガベージコレクション(4)のJavaのコードを修正

- src/problems/problemData.ts
> fix: 2-3 fixed-view-variable

- src/problems/problemData.ts
> feat: add 5 problems of Lecture 6

- src/problems/problemData.ts
- src/problems/traceProgram.ts
- tests/unit/traceProgram.test.ts
> feat: add advanced problems of Lecture 7
